spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: 1111
    driverClassName: org.postgresql.Driver

server:
  servlet:
    contextPath: /school